run:
  modules-download-mode: "readonly"
  timeout: "5m"

linters:
  disable-all: true
  presets:
    - bugs
    - unused
  enable:
    - cyclop
    - dupl
    - errname
    - gochecknoinits
    - gochecknoglobals
    - gosimple
    - misspell
